### ISSUE TITLE
set order option

### ISSUE THREAD

**Issue by maenpaa24** [bootoption/bootoption#4]
Hi!

From my understanding of the manual if I want to give the third position in the bootorder to the boot option "Boot0080" I should do:

`bootoption set -n Boot0080 -o 3`

However, what it does is setting as the first boot option the one with label Boot0003. In the case Boot0003 does not exist it says `error: variable Boot0003 not found`

I am not sure if it is a bug or a mistake in the sintaxis.

The real line I write is:

`bootoption set -n Boot0080 --active 1 -o 3`

otherwise it prompts:

`-n, --name' used without required accompanying options`

Although I can not see the need for the --active option from the manual.

**Comment by bootoption** [comment]
```
bootoption set -o
```
takes as its arguments an array of load options, and sets the ```BootOrder``` variable directly
```
bootoption set -o Boot0001 Boot0080 Boot0002
```
while
```
bootoption order ...
```
takes 2 arguments:
- the current position of a load option already in the boot order; and
- the desired new position of this load option in the boot order

```
set -n BootXXXX ...
```
is used in conjunction with ```-d``` and ```-a``` for setting the description or arguments for that load option, and in conjunction with ```--active``` and ```--hidden``` for setting those option attributes.

**Comment by maenpaa24** [comment]
It was a syntaxis mistake indeed. Thanks for the clarification.
