### ISSUE TITLE
AppleAPFSContainer is not supported?

### ISSUE THREAD

**Issue by TheoSan-13** [bootoption/bootoption#7]
Below is how I tried to create a new option:	

theo@theos-mac-mini ~ % csrutil status                                                                                   
System Integrity Protection status: disabled.
	
theo@theos-mac-mini ~ % sudo bootoption create -l /Volumes/MacOnTosh/System/Library/CoreServices/boot.efi -d "Apple MacOnTosh"
error: parent IOReg node's class of AppleAPFSContainer for volume '/' is not supported [(): makeLoader(path:), file: LoaderFactory.swift]

**Comment by bootoption** [comment]
It's not supported here, only generic "EFI Boot" from EFI system partitions. For HFS+/APFS bootability you should use the startup disk pref pane or bless command.
