### ISSUE TITLE
Releases should offer a raw binary download

### ISSUE THREAD

**Issue by Ecco** [bootoption/bootoption#9]
macOS pkg file are hard to uninstall. If you simply want to give this tool a try, it's much easier to just download a binary file, run it, and delete it afterwards if needed. Also you can place it in whichever directory you like (e.g. `~/local/bin`).

**Comment by bootoption** [comment]
Agreed and binaries uploaded, thanks.

**Comment by Ecco** [comment]
Awesome. Thanks!
